feat: histogram2, test code 추가, 데이터 type 추가
TeamCrazyPerformance/2023-spring-study pull request #24
Opened 2023-03-17 14:01 UTC by cshooon

Chatgpt가 잘 짜줘서 생각보다 금방 짰네요. 거짓말을 하긴 하지만 앞으로 정말 많이 쓰일 것 같아요!!
test code 짜는 거 처음 해봐서 신기했어요. 소공 때 pytest 써야 되는데 도움이 많이 될 것 같아요!!
오늘 디코로 파일 경로 잡아주셔서 감사합니다.
spring 강의 들을려고 하는데 김영한님 괜찮은지 궁금해요!!
https://velog.io/@blublue_02/Exception-and-Test

2023-03-17 14:40 UTC, wlsh44 requested changes
고생하셨습니다! chatGPT도 잘 사용하면 좋은 도구가 되긴 하는데 개인적으로 아직까지는 좋은 효율이 나오지는 않는 것 같다는 생각이 드네요..

테스트 코드 작성해보는게 이번 기회에 도움이 되었다니 다행입니다 ㅎㅎ

개인적으로 코드를 보면서 느낀 점은 약간 '코드가 전체적으로 많이 길다' 였습니다!
코드가 길어진다는 뜻은 하나의 메서드가 여러가지 일을 하고 있을 확률이 높다는 것이니 메서드 분리를 하는 걸 추천드려요

이번에 리뷰 드린 부분 보고 수정해주심 됩니다~

****

스프링 공부하는데는 김영한님 강의만한게 없습니다(조금 비싸긴 하지만) ㅋㅋㅋ 저도 모든 강의 다 구매해서 지금 3개 남겨두고 있어요!

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/Main.java
> +    private static final String AVG_MESSAGE = "데이터 양에 대한 평균입니다.";
이렇게 메시지를 상수 처리한 부분 너무 좋았습니다!! 👍 👍
다만 굳이 이 상수를 Main에 두고 파라미터로 넘겨야 하나? 라는 의문점이 들었어요

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/Main.java
>      }
> - 함수(또는 메서드)의 길이가 15라인을 넘어가지 않도록 구현한다. )
>  - 함수(또는 메서드)가 한 가지 일만 잘 하도록 구현한다.)
> - else 예약어를 쓰지 않는다.

😢😢

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/Main.java
> +            writer.close();
close하는 구문 너무 좋았네요 👍 👍 
자바 7 이후에 나온 자동으로 리소스 반납해주는 기능도 한 번 찾아보시길 바랍니다!
키워드: try with resource

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/domain/Histogram.java
> +    public static String getAvg(ArrayList<Integer> data)
모든 메서드가 public static인 이유가 있나요?

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/domain/Histogram.java
> +        return "" + avg;
문자열로 만들고 싶어서 "" + avg를 해주신 것 같은데 개인적으로는 String.valueOf() 라는 메서드를 추천드립니다~

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/view/InputView.java
> +                    throw new IllegalArgumentException("[ERROR] 데이터의 양은 음수일 수 없습니다.");
공통 피드백 때 뎁스가 너무 깊어질 경우 가독성에 좋지 않고, 메서드로 분리를 하면 좋다는 피드백을 드렸었던 것 같아요 ㅎㅎ

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/view/InputView.java
> +    public static ArrayList<Integer> inputString(BufferedReader reader) throws IOException {
저번 리뷰 때 리턴 값이 ArrayList일 때 생기는 단점에 대해 생각해보라고 리뷰를 드렸던 것 같은데 혹시 생각해보셨나요?

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/view/InputView.java
> +        outputview.outputView(writer, message);
outputView의 모든 메서드가 static인데 굳이 OutputView라는 객체를 만들 필요는 없을 것 같아요

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/test/java/inputViewTest.java
> +}
테스트 코드 너무 잘 작성해주셨네요!
예외가 발생하는 경우의 테스트 코드도 작성해보시면 좋을 것 같아요

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/view/InputView.java
> +        Pattern pattern = Pattern.compile("-?\\d+");
해당 표현식이 어떤 의미인지 파악이 잘 가지 않네요..ㅠ

2023-03-17 14:40 UTC, wlsh44 commented on java-histogram/src/main/java/org/example/Main.java
> +                    outputview.outputView(writer, data.get(0), DataType.TYPE_1.name(), histogram);
만약 DataType이 더 늘어난다면 해당 부분이 if else if...의 반복이 될텐데 이를 해결할 수 있는 방법은 없을까요?

2023-03-22 06:51 UTC, cshooon commented
코드 고치는 것이 도움이 많이 되네요.
알려주셔서 감사합니다!!!

https://velog.io/@blublue_02/%EC%A0%91%EA%B7%BC-%EC%A0%9C%ED%95%9C%EC%9E%90-interface-abstract

2023-03-24 14:30 UTC, merged