feat: List database 추가
TeamCrazyPerformance/2023-spring-study pull request #29
Opened 2023-03-27 14:12 UTC by cshooon

DAO 구현하는 것이 어렵네요. Map도 똑같은 방향으로 하면 될 것 같아서 미리 올립니다.
또 충돌나네요 ㅠㅠㅠ.....

2023-03-28 00:26 UTC, wlsh44 requested changes
main 메서드가 좀 긴거 빼고는 잘 하고 계신 것 같아요!
이는 main이 너무 많은 책임(기능)을 가진다는 뜻과 비슷하다고 볼 수 있습니다. 그래서 이전 과제에서 했던 것처럼 view를 분리하고, 기능을 조금씩 다른 클래스에 분리해보는건 어떨까요?
그리고 코드를 작성할때는 항상 다른 사람이 내 코드를 볼 때 어떤 생각이 들까? 를 염두에 두고 작성을 하면 좋습니다.
operation 스위치문 같은 경우도 단순 1, 2와 같은 숫자보다 이전에 배운 enum을 이용해서 SAVE, FIND 등 이름을 주면 더 좋을 것 같아요 ㅎㅎ

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/Main.java
> +    }
엄청난 절차지향 코드군요!! ㅋㅋㅋㅋㅋ
우선 저번 과제때 했던 것처럼 view 부터 분리하는 작업을 해보는건 어떨까요?

그리고 요구사항 15줄은 지켜주실거라 믿습니다 ㅎㅎ

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/dao/MyListDao.java
> +    }
지금 이름으로 검색하는 부분이 메서드마다 중복되는 것 같은데 하나의 메서드로 분리할 수 있지 않을까요?

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/dao/MyMapDao.java
> +            peopleData.put(person.getName(), person);
key 값을 이름으로 하신 것 같은데 그렇다면 필드의 key 타입도 String으로 바꿔주면 좋을 것 같아요

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/dao/MyListDao.java
> +        return null;
다른 메서드도 마찬가지지만 지금같이 '조회'라는 특정 기능을 가진 메서드라면 해당 이름을 가진 사람이 없는 경우 예외 상황이라고 할 수 있습니다.
따라서 null을 리턴하는 것보다 예외를 발생시키는게 어떨까요? null은 해당 메서드를 사용하는 클라이언트에서 쉽게 nullPointException이 발생할 수 있기 때문에 리턴값에 들어가면 좋지 않기도 합니다

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/dao/MyDao.java
> +    Person update(String name, LocalDate birthday, String introduction);
생일을 LocalDate로 처리하신 부분 좋았습니다!
자바에는 Date와 LocalDate가 있는데 어떤 차이가 있을까요?

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/domain/Person.java
> +        int age = Period.between(birthDate, today).getYears();
Period 패키지는 저도 처음 알았네요 👍

2023-03-28 00:26 UTC, wlsh44 commented on MyDao/src/main/java/org/example/domain/Person.java
> +    }
단순 setter를 통해 업데이트를 한게 아니라 update 메서드를 따로 만들어준 점 너무 좋았습니다! 👍👍👍
이처럼 객체가 본인의 상태 관리를 외부에 맡기는게 아니라 스스로 관리하도록 하는게 객체지향 설계에서의 중요한 점입니다.
그리고 setter라는 단순 값 설정 메서드보다 update라는 특정 목적을 명시해주는 점도 아주 중요해요 ㅎㅎ

2023-03-28 08:53 UTC, shchooii commented on MyDao/src/main/java/org/example/dao/MyDao.java
> +    Person update(String name, LocalDate birthday, String introduction);
LocalDate는 생성한 후에 값을 변경할 수 없고 Date는 값을 변경할 수 있습니다.
특정 시점을 날짜와 시간으로 모두 표현해야 하는 경우에는 Date를 사용할 수 있지만, 시간 없이 날짜만 나타내면 되는 경우에는 LocalDate를 사용하는 것이 좋다고 합니다. 또한 Java 8 이상으로 작업하는 경우 java.util 패키지의 이전 Date 클래스 대신 java.time 패키지 및 LocalDate를 사용하는 것이 좋다고 합니다. 처음 알았네요... ㅋㅋ

2023-03-28 08:57 UTC, shchooii commented on MyDao/src/main/java/org/example/domain/Person.java
> +    }
inputView와 outputView로 분리 진행했고 아직 Map은 못 짰어요 ㅠㅠ 질문이 2개 있습니다.
![image](https://user-images.githubusercontent.com/113033780/228183686-5ea900c5-5152-49ef-a841-42c3af3b2172.png)
1. 이러면 error catch 안 된 건가요??
2. case 3에서 얕은 복사해서 값을 넘겨주려고 하는데 얕은 복사는 어떻게 하나요? 객체를 객체에 등호로 옮기면 안되더라고요...ㅠㅠㅠ

2023-03-30 13:35 UTC, wlsh44 requested changes
코드가 점점 좋아지고 있는 것 같아서 좋네요 👍 main만 어떻게 해결하면...ㅎㅎ
그리고 메서드마다 여러 기능이 있는 부분을 조금만 분리를 하면 코드가 훨씬 깔끔해질 것 같아요!!
다음 PR때는 Map 부분도 완성이 되어있을거라 믿고 있겠습니다!
고생하셨어요~

2023-03-30 13:35 UTC, wlsh44 commented on MyDao/src/main/java/org/example/domain/Person.java
> +    }
1. 넵 이 경우에는 catch가 되지 않았네요
2. 자바는 따로 깊은 복사하는 기능을 만들지 않는 이상 모두 얕은 복사처리 됩니다! 아마 지금 안되신 부분은 리스트에서 가져온 person이 다른 메서드로 넘어가면서 call by value를 통해 person 객체를 가리키는 포인터가 복사되고, 그 객체에 = 를 이용해 값을 대입하면서 복사된 포인터가 다른 객체를 가리키게 된 거라고 생각이 되네요. 
이 부분이 이해가 잘 안가신다면 자바의 call by value에 대해서 공부해보시면 좋을 것 같아요~

2023-03-30 13:35 UTC, wlsh44 commented on MyDao/src/main/java/org/example/Main.java
> +                }
만약 여기에 Map과 관련된 기능이 추가된다면 코드가 엄청 길어지지 않을까요?
여기에 다른 디비 구조가 추가된다면??
dao를 인터페이스로 만든 이유에 대해서 생각해보시면 좋을 것 같아요!

2023-03-30 13:35 UTC, wlsh44 commented on MyDao/src/main/java/org/example/Main.java
> +                    bw.flush();
write와 flush가 반복되고 있는데 이 부분도 하나의 함수로 빼면 중복을 줄일 수 있을 것 같아요 ㅎㅎ

2023-03-30 13:35 UTC, wlsh44 commented on MyDao/src/main/java/org/example/Main.java
> +    }
222

2024-12-31 12:38 UTC, closed without merging